export const CONTACT_ADD_SUCCESS = 'CONTACT_ADD_SUCCESS';
export const CONTACT_ADD_ERROR = 'CONTACT_ADD_ERROR';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const REMOVE_USERS_SUCCESS = 'REMOVE_USERS_SUCCESS';
export const REMOVE_USERS_FAIL = 'REMOVE_USERS_FAIL';

export const EDIT_START = 'EDIT_START';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const EDIT_USERS_FAIL = 'EDIT_USERS_FAIL';
